FROM openjdk:17-jdk-alpine

# 애플리케이션 JAR 복사
COPY build/libs/*.jar app.jar

# 환경 변수 설정
ENV CHATBOT_APIURL=${CHATBOT_APIURL}
ENV CHATBOT_SECRETKEY=${CHATBOT_SECRETKEY}
ENV STT_APIURL=${STT_APIURL}
ENV STT_SECRETKEY=${STT_SECRETKEY}
ENV TTS_APIURL=${TTS_APIURL}
ENV TTS_APIKEYID=${TTS_APIKEYID}
ENV TTS_SECRETKEY=${TTS_SECRETKEY}

# Spring Boot 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "/app.jar"]
