FROM openjdk:17-jdk-alpine

COPY build/libs/*.jar app.jar

ARG CHATBOT_APIURL
ARG CHATBOT_SECRETKEY
ARG STT_APIURL
ARG STT_SECRETKEY
ARG TTS_APIURL
ARG TTS_APIKEYID
ARG TTS_SECRETKEY

ENV CHATBOT_APIURL=$CHATBOT_APIURL
ENV CHATBOT_SECRETKEY=$CHATBOT_SECRETKEY
ENV STT_APIURL=$STT_APIURL
ENV STT_SECRETKEY=$STT_SECRETKEY
ENV TTS_APIURL=$TTS_APIURL
ENV TTS_APIKEYID=$TTS_APIKEYID
ENV TTS_SECRETKEY=$TTS_SECRETKEY

ENTRYPOINT ["java", "-jar", "/app.jar"]