spring:
  application:
    name: chatbot_api
  config:
    import: optional:file:.env[.properties]

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8086

CHATBOT_APIURL: ${CHATBOT_APIURL}
CHATBOT_SECRETKEY: ${CHATBOT_SECRETKEY}
STT_APIURL: ${STT_APIURL}
STT_SECRETKEY: ${STT_SECRETKEY}
TTS_APIURL: ${TTS_APIURL}
TTS_APIKEYID: ${TTS_APIKEYID}
TTS_SECRETKEY: ${TTS_SECRETKEY}