spring:
  application:
    name: chatbot_api
  config:
    import: optional:file:.env[.properties]

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8081

