spring:
  application:
    name: chatbot_api

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8081

chatbot:
  apiurl: ${CHATBOT_APIURL}
  secretkey: ${CHATBOT_SECRETKEY}
stt:
  apiurl: ${STT_APIURL}
  secretkey: ${STT_SECRETKEY}
tts:
  apiurl: ${TTS_APIURL}
  apikeyid: ${TTS_APIKEYID}
  secretkey: ${TTS_SECRETKEY}
